version: '2'

services:

  client:
    build: ./Frontend
    ports:
      - 8080:8080
#  environment:
 #     - SERVER_URL=http://backend:9000

  backend:
    build: ./Backend
    ports:
      - 9000:9000
